from collections.abc import Sequence
from typing import Protocol, runtime_checkable

from loregraph.schemas.agent import (
    AgentReviewPayload,
    AgentSessionOut,
    AgentSessionStatus,
)
from loregraph.schemas.attachment import AttachmentOut
from loregraph.schemas.edge import EdgeCreate, EdgeOut, EdgeUpdate
from loregraph.schemas.entity import EntityCreate, EntityOut, EntityUpdate
from loregraph.schemas.knowledge import KnowledgeSourceOut
from loregraph.schemas.project import ProjectCreate, ProjectOut, ProjectUpdate


@runtime_checkable
class ProjectStore(Protocol):
    async def list_projects(self) -> list[ProjectOut]: ...
    async def create(self, data: ProjectCreate) -> ProjectOut: ...
    async def get(self, project_id: str) -> ProjectOut: ...
    async def update(self, project_id: str, data: ProjectUpdate) -> ProjectOut: ...
    async def delete(self, project_id: str) -> None: ...
    async def exists(self, project_id: str) -> bool: ...


@runtime_checkable
class EntityStore(Protocol):
    async def list_entities(
        self, project_id: str, entity_type: str | None = None
    ) -> list[EntityOut]: ...
    async def create(self, data: EntityCreate, project_id: str) -> EntityOut: ...
    async def get(self, entity_id: str) -> EntityOut: ...
    async def get_many(self, entity_ids: Sequence[str]) -> list[EntityOut]: ...
    async def exists(self, entity_id: str) -> bool: ...
    async def update(self, entity_id: str, data: EntityUpdate) -> EntityOut: ...
    async def delete(self, entity_id: str) -> None: ...
    async def set_icon(
        self, entity_id: str, attachment_id: str | None
    ) -> EntityOut: ...


@runtime_checkable
class EdgeStore(Protocol):
    async def get(self, edge_id: str) -> EdgeOut: ...
    async def list_for_entity(self, entity_id: str) -> list[EdgeOut]: ...
    async def list_all(
        self, project_id: str, edge_types: frozenset[str] | None = None
    ) -> list[EdgeOut]: ...
    async def create(self, data: EdgeCreate, project_id: str) -> EdgeOut: ...
    async def update(self, edge_id: str, data: EdgeUpdate) -> EdgeOut: ...
    async def delete(self, edge_id: str) -> None: ...


@runtime_checkable
class AgentSessionStore(Protocol):
    async def create(self, project_id: str, thread_id: str) -> AgentSessionOut: ...
    async def get(self, thread_id: str) -> AgentSessionOut: ...
    async def list_for_project(self, project_id: str) -> list[AgentSessionOut]: ...
    async def update(
        self,
        thread_id: str,
        *,
        status: AgentSessionStatus | None = None,
        title: str | None = None,
        input_tokens: int | None = None,
        output_tokens: int | None = None,
        committed_entity_ids: list[str] | None = None,
        review: AgentReviewPayload | None = None,
        clear_review: bool = False,
    ) -> AgentSessionOut: ...


@runtime_checkable
class AttachmentStore(Protocol):
    async def create(
        self,
        entity_id: str,
        original_filename: str,
        content_type: str,
        content: bytes,
    ) -> AttachmentOut: ...
    async def list_for_entity(self, entity_id: str) -> list[AttachmentOut]: ...
    async def delete(self, attachment_id: str) -> None: ...


@runtime_checkable
class KnowledgeSourceStore(Protocol):
    async def create(
        self,
        project_id: str,
        original_filename: str,
        content_type: str,
        content: bytes,
    ) -> KnowledgeSourceOut: ...
    async def list_for_project(self, project_id: str) -> list[KnowledgeSourceOut]: ...
    async def get(self, source_id: str) -> KnowledgeSourceOut: ...
    async def update_status(
        self,
        source_id: str,
        *,
        status: str,
        error: str | None = None,
        chunk_count: int | None = None,
    ) -> KnowledgeSourceOut: ...
    async def delete(self, source_id: str) -> None: ...
