from collections.abc import Sequence
from typing import Protocol, runtime_checkable

from loregraph.schemas.attachment import AttachmentOut
from loregraph.schemas.edge import EdgeCreate, EdgeOut, EdgeUpdate
from loregraph.schemas.entity import EntityCreate, EntityOut, EntityUpdate


@runtime_checkable
class EntityStore(Protocol):
    async def list_entities(
        self, entity_type: str | None = None
    ) -> list[EntityOut]: ...
    async def create(self, data: EntityCreate) -> EntityOut: ...
    async def get(self, entity_id: str) -> EntityOut: ...
    async def get_many(self, entity_ids: Sequence[str]) -> list[EntityOut]: ...
    async def exists(self, entity_id: str) -> bool: ...
    async def update(self, entity_id: str, data: EntityUpdate) -> EntityOut: ...
    async def delete(self, entity_id: str) -> None: ...
    async def set_icon(
        self, entity_id: str, attachment_id: str | None
    ) -> EntityOut: ...


@runtime_checkable
class EdgeStore(Protocol):
    async def list_for_entity(self, entity_id: str) -> list[EdgeOut]: ...
    async def list_all(
        self, edge_types: frozenset[str] | None = None
    ) -> list[EdgeOut]: ...
    async def create(self, data: EdgeCreate) -> EdgeOut: ...
    async def update(self, edge_id: str, data: EdgeUpdate) -> EdgeOut: ...
    async def delete(self, edge_id: str) -> None: ...


@runtime_checkable
class AttachmentStore(Protocol):
    async def create(
        self,
        entity_id: str,
        original_filename: str,
        content_type: str,
        content: bytes,
    ) -> AttachmentOut: ...
    async def list_for_entity(self, entity_id: str) -> list[AttachmentOut]: ...
    async def delete(self, attachment_id: str) -> None: ...
